name: plugin release package
on:
  push:
    branches:
      - main
jobs:
  build:
    name: plugin relase package ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [ amd64 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node modules admin
        uses: actions/cache@v3
        with:
          path: src/main/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/main/frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: |
          bash -e ./mvnw clean package assembly:single -DoutputDirectory=/tmp/download/plugin
          bash bin/upload-bin.sh ${{ secrets.SECRET_ID }} ${{ secrets.SECRET_KEY }} ${{ secrets.BUCKET }} /tmp/download plugin ${{ secrets.HOST }}